loops:
  lobby_hz: 5.0
  race_hz: 60.0

lobby:
  max_players: 8 #enunciado: 8
  between_races_sec: 5.0
  max_race_time_sec: 600.0 #enunciado: 10mins

physics:
  time_step: 0.0166667   # 1/60
  sub_step_count: 4

car_handling:
  base_health: 100.0
  max_fwd_speed: 50.0
  max_bck_speed: -10.0
  engine_impulse: 800.0
  brake_accel: 100.0
  max_angular_vel: 2.5
  lateral_damp: 9.0

collisions:
  building:
    min_impact_speed: 1.5
    base_damage_factor: 0.5
    min_frontal_alignment: 0.7
    frontal_multiplier: 4.0
    velocity_damp_factor: 0.5

  car:
    min_impact_speed: 1.0
    base_damage_factor: 0.4
    min_frontal_alignment: 0.7
    frontal_multiplier: 4.0
    velocity_damp_factor: 0.4

upgrades:
  - type: ENGINE_FORCE
    factor: 2.5
    penalty: 8.0

  - type: HEALTH
    factor: 1.5
    penalty: 5.0

  - type: SHIELD
    factor: 0.7
    penalty: 2.0

  - type: DAMAGE
    factor: 2.0
    penalty: 3.0

cheats:
  enabled: true
  allow_health_cheat: true
  allow_free_speed_cheat: true
  allow_next_checkpoint_cheat: true
  allow_win_race_cheat: true
  allow_lost_race_cheat: true

